version: '3.9'

volumes:
  db_servicos_data:
  rabbitmq_data:
networks:
  fiap-order:
    external: false

services:
  db-servicos:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_servicos_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - fiap-order

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - fiap-order
  
  pedido-ms-orders:
    build: pedido/
    ports:
      - "8181:8080"
    depends_on:
      - db-servicos
      - rabbitmq
    networks:
      - fiap-order
  

  
  #test-pedido:
    #build:
      #context: pedido/
      #dockerfile: Dockerfile.test
    #volumes:
      #- ./pedido:/app
      #- ./reports:/reports